# Copyright (C) 2018 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh worker StatefulSet: 1

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-worker-1
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
      node-type: worker
      sts-id: '1'
  serviceName: wazuh-cluster
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: wazuh-manager
        node-type: worker
        sts-id: '1'
      name: wazuh-manager-worker-1
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: sts-id
                      operator: In
                      values:
                        - '0'
                topologyKey: kubernetes.io/hostname
      volumes:
        - name: config
          configMap:
            name: wazuh-manager-worker-1-conf
        - name: filebeat-config-volume
          configMap:
            name: filebeat-config
        - name: filebeat-certs
          secret:
            secretName: filebeat-certs-secret
      containers:
        - name: wazuh-manager
          image: 'wazuh-docker_wazuh:latest'
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
          env:
            - name: ELASTICSEARCH_URL
              value: 'https://elasticsearch:9200'
            - name: SSL_CERTIFICATE_AUTHORITIES
              value: '/etc/filebeat/root-ca.pem'
            - name: USERNAME
              value: admin
            - name: PASSWORD
              value: admin              
          volumeMounts:
            - name: config
              mountPath: /wazuh-config-mount/etc/ossec.conf
              subPath: ossec.conf
              readOnly: true
            - name: wazuh-manager-worker
              mountPath: /var/ossec/data
            - mountPath: /etc/filebeat/root-ca.pem
              name: filebeat-certs
              subPath: root-ca.pem
          ports:
            - containerPort: 1514
              name: agents-events
            - containerPort: 1516
              name: cluster
  volumeClaimTemplates:
    - metadata:
        name: wazuh-manager-worker
        namespace: wazuh
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gp2-encrypted-retained
        resources:
          requests:
            storage: 10Gi
