# Copyright (C) 2018 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh master StatefulSet

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
  serviceName: wazuh-cluster
  template:
    metadata:
      labels:
        app: wazuh-manager
      name: wazuh-manager
    spec:
      volumes:
        - name: config
          configMap:
            name: wazuh-manager-conf
      containers:
        - name: wazuh-manager
          image: 'xr09/wazuh:3.11.3_7.5.2'
          resources:
            requests:
              cpu: 2
              memory: 1024Mi
            limits:
              cpu: 2
              memory: 2048Mi
          volumeMounts:
            - name: config
              mountPath: /wazuh-config-mount/etc/ossec.conf
              subPath: ossec.conf
              readOnly: true
            - name: wazuh-manager-api
              mountPath: /var/ossec/api/configuration
            - name: wazuh-manager-etc
              mountPath: /var/ossec/etc
            - name: wazuh-manager-logs
              mountPath: /var/ossec/logs
            - name: wazuh-manager-queue
              mountPath: /var/ossec/queue
            - name: wazuh-manager-multigroups
              mountPath: /var/ossec/var/multigroups
            - name: wazuh-manager-integrations
              mountPath: /var/ossec/integrations
            - name: wazuh-manager-active-response
              mountPath: /var/ossec/active-response/bin
            - name: wazuh-manager-wodles
              mountPath: /var/ossec/wodles
            - name: wazuh-manager-filebeat-etc
              mountPath: /etc/filebeat
            - name: wazuh-manager-filebeat-var
              mountPath: /var/lib/filebeat
          ports:
            - containerPort: 1515
              name: registration
            - containerPort: 1514
              name: logging
            - containerPort: 55000
              name: api
  volumeClaimTemplates:
    - metadata:
        name: wazuh-manager-api
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi
    - metadata:
        name: wazuh-manager-etc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Mi
    - metadata:
        name: wazuh-manager-logs
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 200Mi
    - metadata:
        name: wazuh-manager-queue
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Mi
    - metadata:
        name: wazuh-manager-multigroups
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi
    - metadata:
        name: wazuh-manager-integrations
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi
    - metadata:
        name: wazuh-manager-active-response
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi
    - metadata:
        name: wazuh-manager-wodles
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 300Mi
    - metadata:
        name: wazuh-manager-filebeat-etc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi
    - metadata:
        name: wazuh-manager-filebeat-var
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
