apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: wazuh
data:
  elasticsearch.yml: |-
    opendistro_security.ssl.transport.pemcert_filepath: /usr/share/elasticsearch/config/node.pem
    opendistro_security.ssl.transport.pemkey_filepath: /usr/share/elasticsearch/config/node-key.pem
    opendistro_security.ssl.transport.pemtrustedcas_filepath: /usr/share/elasticsearch/config/root-ca.pem
    opendistro_security.ssl.transport.enforce_hostname_verification: false
    opendistro_security.ssl.http.enabled: true
    opendistro_security.ssl.http.pemcert_filepath: /usr/share/elasticsearch/config/node.pem
    opendistro_security.ssl.http.pemkey_filepath: /usr/share/elasticsearch/config/node-key.pem
    opendistro_security.ssl.http.pemtrustedcas_filepath: /usr/share/elasticsearch/config/root-ca.pem
    opendistro_security.allow_default_init_securityindex: true
    opendistro_security.authcz.admin_dn:
      - CN=mydomain2.com,O=MyOrg,ST=CA,C=US
    opendistro_security.nodes_dn:
      - CN=elasticsearch,O=MyOrg2,ST=a,C=ES
      - CN=kibana,O=MyOrg22,ST=a,C=ES
    opendistro_security.audit.type: internal_elasticsearch
    opendistro_security.enable_snapshot_restore_privilege: true
    opendistro_security.check_snapshot_restore_write_privileges: true
    opendistro_security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
    cluster.routing.allocation.disk.threshold_enabled: false
    node.max_local_storage_nodes: 3
    opendistro_security.audit.config.disabled_rest_categories: NONE
    opendistro_security.audit.config.disabled_transport_categories: NONE
    
