# Copyright (C) 2018 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Kibana Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-kibana
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-kibana
  template:
    metadata:
      labels:
        app: wazuh-kibana
      name: wazuh-kibana
    spec:
      containers:
        - name: wazuh-kibana
          image: 'wazuh-docker_kibana:latest'
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 400m
              memory: 1024Mi
          ports:
            - containerPort: 5601
              name: kibana
          env:
            - name: NODE_OPTIONS
              value: '--max-old-space-size=512'
            - name: CURL_PARAMETERS
              value: "--cacert /usr/share/kibana/config/root-ca.pem -u admin:admin -k"
            - name: ELASTICSEARCH_URL
              value: "https://elasticsearch:9200"
          volumeMounts:
            - mountPath: /usr/share/kibana/config/kibana.yml
              name: kibana-configuration-volume
              subPath: kibana.yml
            - mountPath: /usr/share/kibana/config/node2.pem
              name: kibana-certs
              subPath: node2.pem
            - mountPath: /usr/share/kibana/config/node-key2.pem
              name: kibana-certs
              subPath: node-key2.pem
            - mountPath: /usr/share/kibana/config/root-ca.pem
              name: kibana-certs
              subPath: root-ca.pem
      volumes:
        - name: kibana-certs
          secret:
            secretName: kibana-certs-secret
        - name: kibana-configuration-volume
          configMap:
            name: kibana-config
